services:
  - type: web
    name: jarvis-tts
    env: python
    plan: free
    buildCommand: chmod +x start.sh && pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8000